export const data = [
  // Villes de Madagascar
  'Antananarivo',
  'Tuléar',
  'Fianarantsoa',
  'Majunga',
  'Diego Suarez',
  'Toamasina',
  'Morondava',
  'Antsirabe',
  'Nosy Be',
  'Manakara',

  // Villes d'Europe
  'Paris',
  'Berlin',
  'Madrid',
  'Rome',
  'Lisbonne',
  'Londres',
  'Bruxelles',
  'Amsterdam',
  'Vienne',
  'Zurich',
  'Copenhague',
  'Stockholm',
  'Helsinki',
  'Oslo',
  'Athènes',
  'Budapest',
  'Prague',
  'Varsovie',
  'Dublin',
  'Milan',

  // Villes des États-Unis
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Francisco',
  'Seattle',
  'Boston',
  'Miami',
  'Denver',
  'Las Vegas',
  'Atlanta',
  'Detroit',
  'Orlando',
  'Washington, D.C.',
  'San Jose',
];
